from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def choose_provider(provider: str) -> str | None:
    if provider != "auto":
        return provider if shutil.which(provider) else None
    for candidate in ("opencode", "codex"):
        if shutil.which(candidate):
            return candidate
    return None


def build_command(provider: str, prompt_path: Path, cwd: Path, model: str | None = None) -> list[str]:
    if provider == "opencode":
        command = ["opencode", "run", "--prompt-file", str(prompt_path)]
        if model:
            command.extend(["--model", model])
        return command
    if provider == "codex":
        command = [
            "codex",
            "--ask-for-approval",
            "never",
            "exec",
            "-C",
            str(cwd),
            "--sandbox",
            "workspace-write",
        ]
        if model:
            command.extend(["--model", model])
        command.append("-")
        return command
    raise ValueError(f"unsupported AI provider: {provider}")


def run_ai_task(prompt_path: Path, provider: str = "auto", cwd: Path = ROOT, model: str | None = None) -> subprocess.CompletedProcess[str]:
    selected = choose_provider(provider)
    if selected is None:
        return subprocess.CompletedProcess(
            args=[provider],
            returncode=127,
            stdout="",
            stderr="No AI CLI found. Install opencode, or install/login Codex CLI and retry.\n",
        )
    prompt_text = prompt_path.read_text(encoding="utf-8")
    command = build_command(selected, prompt_path, cwd, model)
    input_text = prompt_text if selected == "codex" else None
    return subprocess.run(command, cwd=cwd, input=input_text, text=True, capture_output=True)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run an AI handoff prompt with opencode or Codex CLI")
    parser.add_argument("--prompt-file", required=True, help="Prompt file generated by tools/watch_replays.py")
    parser.add_argument("--provider", choices=("auto", "opencode", "codex"), default="auto", help="AI CLI provider; default auto-detects opencode then codex")
    parser.add_argument("--cwd", default=str(ROOT), help="Working directory for the AI CLI")
    parser.add_argument("--model", help="Optional model name passed through to the AI CLI")
    args = parser.parse_args()

    completed = run_ai_task(Path(args.prompt_file), args.provider, Path(args.cwd), args.model)
    if completed.stdout:
        print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, end="", file=sys.stderr)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
